export const motivationalQuotes: string[] = [
  "O corpo alcança o que a mente acredita.",
  "Sua única competição é quem você era ontem.",
  "Disciplina é fazer o que precisa ser feito mesmo quando você não quer.",
  "A vontade de treinar deve ser maior que a vontade de dar uma desculpa.",
  "Mudar hábitos é difícil, mas continuar onde você está é ainda pior.",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  "Não pare quando estiver cansado, pare quando tiver terminado.",
  "Foco é dizer não para as distrações que te afastam do seu objetivo.",
  "A motivação faz você começar, o hábito faz você continuar.",
  "O seu corpo é o seu maior projeto, trabalhe nele com dedicação.",
  "Se fosse fácil, todo mundo faria.",
  "O suor de hoje é a força de amanhã.",
  "Não espere por inspiração, busque a disciplina.",
  "A dor é temporária, o orgulho de vencer é para sempre.",
  "O fracasso é apenas uma oportunidade de começar de novo com mais inteligência.",
  "Treine para ser a sua melhor versão, não a versão de outra pessoa.",
  "Onde não há esforço, não há crescimento.",
  "Seja mais forte que sua melhor desculpa.",
  "A paciência é a chave para resultados duradouros.",
  "Transforme seus 'eu não consigo' em 'eu vou tentar'.",
  "Um treino de 20 minutos é melhor do que nenhum treino.",
  "Você não precisa ser ótimo para começar, mas precisa começar para ser ótimo.",
  "Daqui a um ano, você vai desejar ter começado hoje.",
  "O primeiro passo é sempre o mais difícil, mas é o mais importante.",
  "Não olhe para o topo da montanha, olhe para o próximo passo.",
  "Devagar e sempre ainda ganha a corrida.",
  "Grandes jornadas começam com pequenos hábitos.",
  "Pare de falar e comece a fazer.",
  "Não desista só porque o progresso está lento.",
  "Cada gota de suor te deixa mais perto da sua meta.",
  "Consistência vence a intensidade a longo prazo.",
  "O hoje é o amanhã que você planejou ontem.",
  "Lembre-se do porquê você começou.",
  "Dias ruins são apenas testes de persistência.",
  "Se você cansar, aprenda a descansar, não a desistir.",
  "O progresso é melhor do que a perfeição.",
  "A cada treino, você está construindo um novo você.",
  "Não deixe um dia ruim se transformar em uma semana ruim.",
  "O impossível é apenas uma opinião.",
  "Você é capaz de muito mais do que imagina.",
  "Coma para nutrir seu corpo, não para alimentar suas emoções.",
  "Abdominais são feitos na cozinha e lapidados na academia.",
  "Saúde não é sobre o peso que você perde, mas sobre a vida que você ganha.",
  "Alimentos saudáveis são o combustível para o seu motor.",
  "Descasque mais, desembrulhe menos.",
  "Água é o melhor suplemento que você pode tomar.",
  "Você é o que você come repetidamente.",
  "Trate seu corpo como um templo, não como uma lixeira.",
  "Equilíbrio é a base de uma vida saudável.",
  "Uma refeição ruim não estraga sua dieta, assim como uma boa não resolve tudo.",
  "Escolha sua saúde todos os dias.",
  "Dormir bem é tão importante quanto treinar pesado.",
  "O segredo da saúde reside na moderação.",
  "Não faça dieta, mude seu estilo de vida.",
  "Seu corpo merece o melhor combustível disponível.",
  "Comer bem é uma forma de autorrespeito.",
  "Nutrição é medicina preventiva.",
  "O resultado vem com o que você faz na maior parte do tempo.",
  "Simplifique sua alimentação e foque no básico.",
  "Saúde é o verdadeiro investimento de longo prazo.",
  "Força não vem da capacidade física, vem de uma vontade indomável.",
  "Desafie-se todos os dias.",
  "A dor do treino é o prazer da vitória.",
  "Supere seus limites e descubra novas capacidades.",
  "Não é sobre ter tempo, é sobre priorizar.",
  "O corpo humano foi feito para se movimentar.",
  "O cansaço físico limpa a mente.",
  "Seja a inspiração que você procura nos outros.",
  "Quando suas pernas cansarem, corra com o coração.",
  "Nada é mais forte do que uma mente decidida.",
  "A zona de conforto é um lugar bonito, mas nada cresce lá.",
  "Você não é um prisioneiro do seu passado, mas o arquiteto do seu futuro.",
  "O suor é a gordura chorando.",
  "Se você quer algo que nunca teve, precisa fazer algo que nunca fez.",
  "A força física se constrói com a resistência mental.",
  "Treine como se fosse o segundo lugar, vença como se fosse o primeiro.",
  "O limite está na sua cabeça.",
  "Transforme seu medo em combustível.",
  "Cada repetição conta.",
  "A vitória pertence aos que perseveram.",
  "Menos desculpas, mais resultados.",
  "Acredite em você.",
  "Movimente-se.",
  "Foco total.",
  "Sem dor, sem ganho.",
  "Apenas faça.",
  "Hoje será épico.",
  "Construa seu legado.",
  "Supere-se.",
  "Viva com propósito.",
  "Mantenha a calma e treine.",
  "Saúde é riqueza.",
  "Escolha ser forte.",
  "Orgulhe-se do seu esforço.",
  "Um dia de cada vez.",
  "Comprometa-se com você.",
  "Seja imparável.",
  "Cultive bons hábitos.",
  "Respire e continue.",
  "O futuro começa agora.",
];

/**
 * Retorna uma frase motivacional determinística para o dia atual.
 * A mesma frase aparece o dia todo e muda automaticamente no dia seguinte.
 */
export function getDailyQuote(date: Date = new Date()): string {
  // Dias desde a época (UTC) — garante uma frase por dia
  const dayIndex = Math.floor(
    Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86_400_000
  );
  const index = ((dayIndex % motivationalQuotes.length) + motivationalQuotes.length) %
    motivationalQuotes.length;
  return motivationalQuotes[index];
}
