/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMedidasRouteImport } from './routes/_authenticated/medidas'
import { Route as AuthenticatedHabitosRouteImport } from './routes/_authenticated/habitos'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/_authenticated/atividades'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMedidasRoute = AuthenticatedMedidasRouteImport.update({
  id: '/medidas',
  path: '/medidas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitosRoute = AuthenticatedHabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtividadesRoute = AuthenticatedAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/medidas': typeof AuthenticatedMedidasRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/medidas': typeof AuthenticatedMedidasRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/_authenticated/habitos': typeof AuthenticatedHabitosRoute
  '/_authenticated/medidas': typeof AuthenticatedMedidasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/atividades' | '/habitos' | '/medidas'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/atividades' | '/habitos' | '/medidas' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/atividades'
    | '/_authenticated/habitos'
    | '/_authenticated/medidas'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medidas': {
      id: '/_authenticated/medidas'
      path: '/medidas'
      fullPath: '/medidas'
      preLoaderRoute: typeof AuthenticatedMedidasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habitos': {
      id: '/_authenticated/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof AuthenticatedHabitosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/atividades': {
      id: '/_authenticated/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AuthenticatedAtividadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRoute
  AuthenticatedHabitosRoute: typeof AuthenticatedHabitosRoute
  AuthenticatedMedidasRoute: typeof AuthenticatedMedidasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAtividadesRoute: AuthenticatedAtividadesRoute,
  AuthenticatedHabitosRoute: AuthenticatedHabitosRoute,
  AuthenticatedMedidasRoute: AuthenticatedMedidasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
