/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMedidasRouteImport } from './routes/_authenticated/medidas'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedHabitosRouteImport } from './routes/_authenticated/habitos'
import { Route as AuthenticatedAtividadeRouteImport } from './routes/_authenticated/atividade'
import { Route as ApiPublicGoogleFitCallbackRouteImport } from './routes/api/public/google-fit-callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMedidasRoute = AuthenticatedMedidasRouteImport.update({
  id: '/medidas',
  path: '/medidas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitosRoute = AuthenticatedHabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtividadeRoute = AuthenticatedAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicGoogleFitCallbackRoute =
  ApiPublicGoogleFitCallbackRouteImport.update({
    id: '/api/public/google-fit-callback',
    path: '/api/public/google-fit-callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/atividade': typeof AuthenticatedAtividadeRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/medidas': typeof AuthenticatedMedidasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/public/google-fit-callback': typeof ApiPublicGoogleFitCallbackRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/atividade': typeof AuthenticatedAtividadeRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/medidas': typeof AuthenticatedMedidasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/google-fit-callback': typeof ApiPublicGoogleFitCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/atividade': typeof AuthenticatedAtividadeRoute
  '/_authenticated/habitos': typeof AuthenticatedHabitosRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/medidas': typeof AuthenticatedMedidasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/google-fit-callback': typeof ApiPublicGoogleFitCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/atividade'
    | '/habitos'
    | '/historico'
    | '/medidas'
    | '/perfil'
    | '/api/public/google-fit-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/atividade'
    | '/habitos'
    | '/historico'
    | '/medidas'
    | '/perfil'
    | '/'
    | '/api/public/google-fit-callback'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/atividade'
    | '/_authenticated/habitos'
    | '/_authenticated/historico'
    | '/_authenticated/medidas'
    | '/_authenticated/perfil'
    | '/_authenticated/'
    | '/api/public/google-fit-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicGoogleFitCallbackRoute: typeof ApiPublicGoogleFitCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medidas': {
      id: '/_authenticated/medidas'
      path: '/medidas'
      fullPath: '/medidas'
      preLoaderRoute: typeof AuthenticatedMedidasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habitos': {
      id: '/_authenticated/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof AuthenticatedHabitosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/atividade': {
      id: '/_authenticated/atividade'
      path: '/atividade'
      fullPath: '/atividade'
      preLoaderRoute: typeof AuthenticatedAtividadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/google-fit-callback': {
      id: '/api/public/google-fit-callback'
      path: '/api/public/google-fit-callback'
      fullPath: '/api/public/google-fit-callback'
      preLoaderRoute: typeof ApiPublicGoogleFitCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAtividadeRoute: typeof AuthenticatedAtividadeRoute
  AuthenticatedHabitosRoute: typeof AuthenticatedHabitosRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedMedidasRoute: typeof AuthenticatedMedidasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAtividadeRoute: AuthenticatedAtividadeRoute,
  AuthenticatedHabitosRoute: AuthenticatedHabitosRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedMedidasRoute: AuthenticatedMedidasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicGoogleFitCallbackRoute: ApiPublicGoogleFitCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
